apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cliet-tableaux-api
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: production-cliet-tableaux-api-cors-prod@kubernetescrd
spec:
  rules:
    - host: api.cliet-tableaux.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cliet-tableaux-api-prod
                port:
                  number: 8080
