apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

nameSuffix: -prod

replicas:
- count: 3
  name: cliet-tableaux-api

resources:
- ../../base
- namespace.yaml
- middleware.yaml

patchesStrategicMerge:
- ingress-patch.yaml
- replicas.yaml

images:
- name: api-image
  newName: ghcr.io/Benjaliette/cliet-tableaux-api
  newTag: main-0fbe13d
