apiVersion: v1
kind: Secret
metadata:
  name: cliet-tableaux-api-secrets
type: Opaque
stringData:
  database-url: "jdbc:postgresql://localhost:5432/tableaux"
  database-username: "postgres"
  database-password: "CHANGE_ME"
  jwt-secret: "CHANGE_ME_LONG_SECRET_KEY"
  cloudinary-secret: "CHANGE_ME_LONG_SECRET_KEY"
  sendgrid-secret: "CHANGE_ME_LONG_SECRET_KEY"
  stripe-secret: "CHANGE_ME_LONG_SECRET_KEY"
  stripe-webhook-secret: "CHANGE_ME_LONG_SECRET_KEY"
